apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  volumes:
  - name: shared-cache
    emptyDir: {}
  - name: azurefile-data
    persistentVolumeClaim:
      claimName: azurefile
  containers:
  - name: pod-1
    image: alpine
    command:
      - bin/sh
    args:
      - -c
      - sleep 1000
    volumeMounts:
      - name: shared-cache
        mountPath: /cache
      - name: azurefile-data
        mountPath: /azurefile-data
  - name: pod-2
    image: alpine
    command:
      - bin/sh
    args:
      - -c
      - sleep 1000
    volumeMounts:
      - name: shared-cache
        mountPath: /cache
      - name: azurefile-data
        mountPath: /azurefile-data

# kubectl exec -it pod --container pod-1 -- bin/sh
# kubectl exec -it pod --container pod-2 -- bin/sh