apiVersion: v1
kind: ServiceAccount
metadata:
  name: apps-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: job-runner-role
rules:
- apiGroups: ["batch"]
  verbs: ["get", "list", "create", "delete"]
  resources: ["jobs"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: log-reader-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: job-runner
subjects:
- kind: ServiceAccount
  namespace: default
  name: apps-sa
roleRef:
  kind: ClusterRole
  name: job-runner-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: log-reader
subjects:
- kind: ServiceAccount
  namespace: default
  name: apps-sa
roleRef:
  kind: ClusterRole
  name: log-reader-role
  apiGroup: rbac.authorization.k8s.io