apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: count-jobs
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: count-jobs
            image: karlkim/rdcli
            args:
            - /bin/sh
            - -c
            - rdcli -h redis.storage llen jobs
          restartPolicy: OnFailure