apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: count-items
  namespace: logging
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: count-items
            image: karlkim/rdcli
            args:
            - /bin/sh
            - -c
            - rdcli -h redis.storage llen items
          restartPolicy: OnFailure