apiVersion: v1
kind: Pod
metadata:
  name: job-api
  labels:
    app: job-api 
spec:
  containers:
    - name: job-api
      image: karlkim/job-api
      command:
      - "dotnet"
      args:
      - "job-api.App.dll"
      ports:
        - containerPort: 5000