apiVersion: batch/v1
kind: Job
metadata:
  name: redis-job
spec:
  completions: 2
  parallelism: 2
  template:
    metadata:
      name: redis-job
    spec:
      containers:
      - name: redis-job
        image: karlkim/redis-job
        command:
          - ./redis-job
        args:
          - --jobname
          - redis-job
      restartPolicy: OnFailure
