apiVersion: batch/v1
kind: Job
metadata:
  name: redis-job
spec:
  completions: 6
  parallelism: 3
  template:
    metadata:
      name: redis-job
    spec:
      containers:
      - name: redis-job
        image: karlkim/redis-job
        command: ["./redis-job", "--jobname", "redis-job"]
      restartPolicy: OnFailure
